# MIT OpenLearning Machine Learning Notes

https://openlearninglibrary.mit.edu/courses/course-v1:MITx+6.036+1T2019/course/

In [2]:
import numpy as np
import matplotlib as plt

## Week 0: Self Assessment

### Chapter 0

3.3) Arrays as lists of lists
Write a function ```array_mult``` that takes two two-dimensional arrays and performs a matrix multiplication, return a new two-dimensional array. Each array should be represented as a list of lists, i.e., as a list of rows, as discussed earlier. For example,

```python
>>> M1 = [[1, 2, 3], [-2, 3, 7]]
>>> M2 = [[1,0,0],[0,1,0],[0,0,1]]
>>> array_mult(M1, M2)
[[1, 2, 3], [-2, 3, 7]]

>>> M3 = [[1], [0], [-1]]
>>> array_mult(M1, M3)
[[-2], [-9]]
```

In [3]:
def array_mult(A, B):
    C = []
    for i in range(0, len(A)):
        c_row = []
        for j in range(0, len(B[0])):
            c_row.append(dot(A[i], get_col(B, j)))
        C.append(c_row)
    return C


def get_col(A, col_idx):
    col = []
    for i in range(len(A)):
        col.append(A[i][col_idx])
    return col

def dot(v1, v2):
    sum = 0
    for e1,e2 in zip(v1,v2):
        sum += e1 * e2
    return sum

In [4]:
M1 = [[1, 2, 3], [-2, 3, 7]]
M2 = [[1,0,0],[0,1,0],[0,0,1]]
print(('Attempt: ' + str(array_mult(M1, M2))).ljust(35), end='\t')
print('Correct: ' + '[[1, 2, 3], [-2, 3, 7]]')

M3 = [[1], [0], [-1]]
print(('Attempt: ' + str(array_mult(M1, M3))).ljust(35), end='\t')
print('Correct: ' + '[[-2], [-9]]')

Attempt: [[1, 2, 3], [-2, 3, 7]]   	Correct: [[1, 2, 3], [-2, 3, 7]]
Attempt: [[-2], [-9]]              	Correct: [[-2], [-9]]


## Week 1: Basics

### Chapter 1

[Chapter_1_Intro.pdf](./MIT_Textbook/Chapter_1_Intro.pdf)

### Chapter 2

[Chapter_2_Linear_Classifications.pdf](./MIT_Textbook/Chapter_2_Linear_Classifications.pdf)

#### Linear Classifications

<center>
<img src="./assets/Week_1/Chapter-2-Linear-Classifications.PNG" height=400px>
<center>

Notice that $\theta^T x + \theta_0$ can be written as the following:
$$
\theta_1 x_1 + \theta_2 x_2 + \theta_0
$$

Thus, the equation of the line above can be written as:
$$
\begin{align*}
\theta_1 x_1 + \theta_2 x_2 + \theta_0 &= 0 \\
x_2 &= \frac{-\theta_1 x_1 - \theta_0}{\theta_2}
\end{align*}
$$

Plugging in our values, we get:
$$
x_2 = \frac{-x_1 - 3}{(3 / 2)} = \frac{2}{3}x_1 - 2
$$

Study Question: What is green vector normal to the hyperplane? Specify it as a column vector.
$$
\vec{n} = \theta^T = \langle -1, 1.5 \rangle
$$

Study Question: What change would you have to make to $\theta, \theta_0$  if you wanted to have the separating hyperplane in the same place, but to classify all the points labeled '+' in the diagram as negative and all the points labeled '-' in the diagram as positive?

We would need to negate $\theta$ and $\theta_0$ such that we would get:
$$
\begin{align*}
-\theta_1 x_1 - \theta_2 x_2 - 3 &= 0 \\
x_2 &= \frac{-\theta_1 x_1 - 3}{\theta_2}
\end{align*}
$$
This way, you get the same line but the normal vector is inversed:
$$
\vec{n} = -\theta^T = \langle 1, -1.5 \rangle
$$

#### Learning Linear Classifications

<center>
<img src="./assets/Week_1/Chapter-2-Learning-Linear-Classifications.png" height=150px>
<center>

Study Question: What do you think happens to $\mathcal{E}n(h)$, where $h$ is the hypothesis returned by Random-Linear-Classifier, as $k$ is increased?  

$\qquad$ As $k$ increases, we can assume that $\mathcal{E}n(h)$ will decrease, as it will give us a higher probability of finding the more minimized loss.
 
Study Question: What properties of $D_n$ do you think will have an effect on $\mathcal{E}n(h)$ ? 

$\qquad$ $D_n$ should have no effect on $\mathcal{E}n(h)$ due to $\mathcal{E}n(h)$ is completely random.

#### Evaluating Linear Classifications

<center>
<img src="./assets/Week_1/Chapter-2-Evaluating-Linear-Classifications.png" height=150px>
<center>

#### Week 1 Exercises

Ex1.1a: 

In two dimensions, $\theta = [\theta_1, \theta_2]$ can define a hyperplane. Let $\theta = [1, 2]$. Give a vector that lies on the hyperplane given by the set of all $x \in \mathbb{R}^2$ such that $\theta^Tx = 0$

Let $x = [x_1, x_2]$ such that we get the following:
$$
\theta^Tx = [\theta_1, \theta_2]^T[x_1, x_2] = \theta_1x_2 + \theta_2x_2 = 1x_1 + 2x_2 = 0
$$

Thus we get the solution for $x$ to be $\mathbf{x = a[2, -1]}$, where a represents a scalar multiple

Ex1.1b. 

Using the same hyperplane, determine a vector that is normal to the hyperplane.

To find a normal vector to the hyper plane, we can take the vector found in the previous problem and dot product it with $\hat{n}$ to get 0.
$$
x \cdot \hat{n} = [2, -1] \cdot [n_1, n_2] = 2n_1 - n_2 = 0
$$

Thus we get the solution for $\hat{n}$ to be $\mathbf{\hat{n} = [1, 2]}$

Ex1.1c. 

Now, in $d$ dimensions, supply the simplified formula for a unit vector normal to the hyperplane in terms of $\theta$ where $\theta \in \mathbb{R}^d$

We can see that because $\theta^Tx = 0$, with $x$ being the vector that lies on the hyperplane, $\theta$.  All vectors normal to $\theta$ is $\theta$.  To find the unit vector, we simply get:
$$
\mathbf{\hat{n}} = \mathbf{\frac{\theta}{||\theta||} }
$$

Ex1.2a. In two dimensions, let $\theta = [3,4]$ and $\theta_0 = 5$. What is the signed perpendicular distance from the hyperplane to the origin? The distance should be positive if the origin is on the positive side of the hyperplane, 0 on the hyperplane and negative otherwise. It may be helpful to draw your own picture of the hyperplane (like the one above but with the right intercepts and slopes) with $\theta = [3,4]$ and $\theta_0 = 5$. Hint -Draw a picture

We can calculate the distance by finding the unit vector projection of some vector x onto the normal vector. Notice also that $\theta^Tx + \theta_0 = 0$ such that $\theta_0 = -\theta^Tx = -x \cdot \theta$

$$
D = \frac{(\langle 0, 0 \rangle - x) \cdot \theta}{||\theta||} = \frac{-x \cdot \theta}{||\theta||} = \frac{\theta_0}{||\theta||} = \frac{5}{5} = 1
$$

Ex1.2b: 

Now, in $d$ dimensions, supply the formula for the signed perpendicular distance from a hyperplane specified by $\theta$, $\theta_0$ to the origin.

We can calculate the unit vector projections to always be for all dimensions $d$:

$$
D = \frac{(\emptyset - x) \cdot \theta}{||\theta||} = \frac{-x \cdot \theta}{||\theta||} = \frac{\theta_0}{||\theta||}
$$

2.1) Array

Provide an expression that sets $A$ to be a $2 \times 3$ numpy array (2 rows by 3 columns), containing any values you wish.

In [5]:
A = 0
A = np.random.randn(2, 3)
print(A)

[[-1.04664989 -0.06042049 -0.96103977]
 [ 0.26557797 -1.44402747 -0.88333023]]


2.2) Transpose

Write a procedure that takes an array and returns the transpose of the array. You can use 'np.transpose' or the '.T', but you may not use a loop.

In [6]:
def tp(A):
    return A.T

print(tp(A))

[[-1.04664989  0.26557797]
 [-0.06042049 -1.44402747]
 [-0.96103977 -0.88333023]]


2.3) Shapes

Let A be a $4 \times 2$ numpy array, B be a $4 \times 3$ array, and C be a $4 \times 1$ array. For each of the following expressions, indicate the shape of the result as a tuple of integers (recall python tuples use parentheses, not square brackets, which are for lists, and a tuple of a single object x is written as (x,) with a comma) or "none" (as a Python string with quotes) if it is illegal.

In [7]:
A = np.random.randn(4, 2)
B = np.random.randn(4, 3)
C = np.random.randn(4, 1)

In [8]:
e23a = C * C
# Element Wise Multiplication - (4, 1)
print(e23a.shape)

try:
    e23b = np.dot(C, C)
except:
    # Dot Product on 2D Matrices results into Matrix Multiplication, thus this is None
    print("\"none\"")

e23c = np.dot(np.transpose(C), C)
# Dot Product on 2D Matrices results into Matrix Multiplication - (1, 1)
print(e23c.shape)

try:
    e23d = np.dot(A, B)
except:
    # Dot Product on 2D Matrices results into Matrix Multiplication, thus this is None
    print("\"none\"")

e23e = np.dot(A.T, B)
# Dot Product on 2D Matrices results into Matrix Multiplication - (2, 3)
print(e23e.shape)

e23f = np.array([1,2,3])
# Arrays are 1D - (3, 1)
print(e23f.shape)

e23g = A[:,1]
# Column 1 as an array - (4, )
print(e23g.shape)

e23h = A[:,1:2]
# Column 1 -> 2 (exclusive) as a 2D Matrix - (4, 1)
print(e23h.shape)


(4, 1)
"none"
(1, 1)
"none"
(2, 3)
(3,)
(4,)
(4, 1)


2.4) Row Vector

Write a procedure that takes a list of numbers and returns a 2D numpy array representing a row vector containing those numbers.

In [9]:
def rv(value_list):
    return np.reshape(value_list, (1, len(value_list)))

print(rv([1,2,3]).shape)


(1, 3)


2.5) Column Vector

Write a procedure that takes a list of numbers and returns a 2D numpy array representing a column vector containing those numbers. You can use the rv procedure.

In [10]:
def cv(value_list):
    return np.reshape(value_list, (len(value_list), 1))

print(cv([1,2,3]).shape)

(3, 1)


2.6) Length

Write a procedure that takes a column vector and returns the vector's Euclidean length (or equivalently, its magnitude) as a scalar. You may not use np.linalg.norm, and you may not use a loop.

In [11]:
def length(col_v):
    return np.sqrt(np.dot(col_v.T, col_v)).item()

print(length(cv([1,2])))


2.23606797749979


2.7) Normalize


Write a procedure that takes a column vector and returns a unit vector in the same direction. You may not use a for loop. Use your length procedure from above (you do not need to define it again).

In [12]:
def normalize(col_v):
    return col_v / length(col_v)

print(normalize(cv([1,2])))

[[0.4472136 ]
 [0.89442719]]


2.8) Indexing

Write a procedure that takes a 2D array and returns the final column as a two dimensional array. You may not use a for loop.

In [13]:
def index_final_col(A):
    A = np.array(A)
    return A[:,len(A[0]) - 1:]

print(index_final_col([[7, 2, 2], [4, 3, 4]]))

[[2]
 [4]]


2.9) Representing Data

Alice has collected weight and height data of 3 people and has written it down below:

Weight, height

150, 5.8

130, 5.5

120, 5.3

She wants to put this into a numpy array such that each row represents one individual's height and weight in the order listed. Write code to set data equal to the appropriate numpy array:

In [14]:
data = 0
data = np.array([[150, 5.8], [130, 5.5], [120, 5.3]])

2.10) Matrix multiplication

Now she wants to compute the sum of each person's height and weight as a column vector by multiplying data by another numpy array. She has written the following incorrect code to do so and needs your help to fix it:

In [15]:
def transform(data):
    return np.dot(data, np.array([1, 1])).reshape(len(data), 1)

transform(data)

array([[155.8],
       [135.5],
       [125.3]])

#### Week 1 Homework

1.1) General hyperplane, distance to point
Let $p$ be an arbitrary point in $R^d$. Give a formula for the signed perpendicular distance from the hyperplane specified by $\theta, \theta_0$ to this point $p$.

<center>
<img src="./assets/Week_1/Homework-1.1.png" height=200px>
<center>

$$
D = \frac{(p - x) \cdot \theta}{||\theta||} = \frac{p^T \cdot \theta + \theta_0}{||\theta||}
$$

1.2) Code for signed distance!

Write a Python function using numpy operations (no loops!) that takes column vectors ($d$ by 1) x and th (of the same dimension) and scalar th0 and returns the signed perpendicular distance (as a 1 by 1 array) from the hyperplane encoded by (th, th0) to $x$. Note that you are allowed to use the "length" function defined in previous coding questions (includig week 1 exercises).

In [16]:
def signed_dist(x, th, th0):
    return (np.dot(x.T, th) + th0) / (length(th))

(x,th,th0)=(np.array([[2],[3]]), np.array([[-3],[-4]]), 5)
print(np.shape(x))
print(np.shape(th))
print(np.shape(th0))
print(signed_dist(x,th,th0).tolist())

(2, 1)
(2, 1)
()
[[-2.6]]


1.3) Code for side of hyperplane

Write a Python function that takes as input
- a column vector x
- a column vector th that is of the same dimension as x
- a scalar th0

and returns

- +1 if x is on the positive side of the hyperplane encoded by (th, th0)
- 0 if on the hyperplane
- -1 otherwise.

The answer should be a 2D array (a 1 by 1). Look at the sign function. Note that you are allowed to use any functions defined in week 1's exercises.

In [17]:
def positive(x, th, th0):
    return np.sign(signed_dist(x, th, th0)).T

(x,th,th0)=(np.array([[-3],[1]]), np.array([[3],[4]]), -5)
print(positive(x,th,th0).tolist())

[[-1.0]]


1.4) Expressions operating on data

We define data to be a 2 by 5 array (two rows, five columns) of scalars. It represents 5 data points in two dimensions. We also define labels to be a 1 by 5 array (1 row, five columns) of 1 and -1 values.

In [18]:
data = np.transpose(np.array([[1, 2], [1, 3], [2, 1], [1, -1], [2, -1]]))
labels = rv([-1, -1, +1, +1, +1])

For each subproblem, provide a Python expression that sets A to the quantity specified. Note that A should always be a 2D numpy array. Only one relatively short expression is needed for each one. No loops!

You can use (our version) of the length and positive functions; they are already defined, don't paste in your definitions. Those functions if written purely as matrix operations should work with a 2D data array, not just a single column vector as the first argument, with no change.

1. A should be a 1 by 5 array of values, either +1, 0 or -1, indicating, for each point in data, whether it is on the positive side of the hyperplane defined by th, th0. Use data, th, th0 as variables in your submission.

In [19]:
A = positive(data, th, th0)

print(A)

[[ 1.  1.  1. -1. -1.]]


2. A should be a 1 by 5 array of boolean values, either True or False, indicating for each point in data and corresponding label in labels whether it is correctly classified by hyperplane th = [1, 1], th0 = -2 . That is, return True when the side of the hyperplane (specified by $\theta, \theta_0$) that the point is on agrees with the specified label.

In [20]:
A = (positive(data, th, th0) * labels) > 0

print(A)

[[False False  True False False]]


1.5) Score

Write a procedure that takes as input
- data: a d by n array of floats (representing n data points in d dimensions)
- labels: a 1 by n array of elements in (+1, -1), representing target labels
- th: a d by 1 array of floats that together with
- th0: a single scalar or 1 by 1 array, represents a hyperplane

and returns the number of points for which the label is equal to the output of the positive function on the point.

Since numpy treats False as 0 and True as 1, you can take the sum of a collection of Boolean values directly.

In [21]:
def score(data, labels, th, th0):
    return np.sum(positive(data, th, th0) * labels > 0)

print(score(data, labels, th, th0))

1


1.6) Best separator

Now assume that we have some "candidate" classifiers that we want to pick the best one out of. Assume you have $ths$, a $d$ by $m$ array of $m$ candidate $\theta$'s (each $\theta$ has dimension $d$ by $1$), and $th0s$, a 1 by $m$ array of the corresponding $m$ candidate $\theta$'s. Each of the $\theta, \theta_0$ pair represents a hyperplane that characterizes a binary classifier.

Write a procedure that takes as input
- data: a d by n array of floats (representing n data points in d dimensions)
- labels: a 1 by n array of elements in (+1, -1), representing target labels
- ths: a d by m array of floats representing $m$ candidate $\theta$'s (each $\theta$ has dimension d by 1)
- th0s: a 1 by m array of the corresponding $m$ candidate $\theta_0$'s.

and finds the hyperplane with the highest score on the data and labels. In case of a tie, return the first hyperplane with the highest score, in the form of
- a tuple of a d by 1 array and an offset in the form of 1 by 1 array.

The function score that you wrote above was for a single hyperplane separator. Think about how to generalize it to multiple hyperplanes and include this modified (if necessary) definition of score in the answer box.

In [39]:
def signed_dist(x, th, th0):
    return (np.dot(x.T, th) + th0) / (np.linalg.norm(th))

data = np.array([ 1,  1,  2,  1,  2, 2,  3,  1, -1, -1]).reshape((2,5))
labels = np.array([-1, -1,  1, 1,  1]).reshape((1,5))
thetas = np.array([ 0.98645534, -0.02061321, -0.30421124, -0.62960452, 0.61617711,  0.17344772, -0.21804797,
                   0.26093651,  0.47179699,  0.32548657, 0.87953335,  0.39605039, -0.1105264,
                   0.71212565, -0.39195678,  0.00999743, -0.88220145, -0.73546501, -0.7769778, -0.83807759]).reshape((2,10))
theta_0s = np.array([ 0.65043158,  0.61626967,  0.84632592, -0.43047804, -0.91768579, -0.3214327,
                     0.0682113,  -0.20678004, -0.33963784,  0.74308104]).reshape((1,10))

def score_mat(data, labels, ths, th0s):
    return np.sum((np.sign(np.dot(ths.T, data)) + th0s.T) == labels, axis=1, keepdims=True)

def best_seperator(data, labels, ths, th0s):
    best_index = np.argmax(score_mat(data, labels, th, th0s))
    return cv(ths[:, best_index]), th0s[:, best_index: best_index + 1]


print(best_seperator(data, labels, thetas, theta_0s))

(array([[0.98645534],
       [0.87953335]]), array([[0.65043158]]))
